development:
  adapter: mysql
  encoding: utf8
  database: rails_dev
  pool: 5
  username: rails
  password: rails
test:
  adapter: mysql
  encoding: utf8
  database: rails_test
  pool: 5
  username: rails
  password: rails
production:
  adapter: mysql
  encoding: utf8
  database: rails_prod
  pool: 5
  username: rails
  password: rails
